name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build backend image
      run: |
        docker build ./backend -t yourdockerhubusername/netflix-backend:latest

    - name: Push backend image
      run: |
        docker push yourdockerhubusername/netflix-backend:latest

    - name: Build frontend image
      run: |
        docker build ./Netflix-Clone -t yourdockerhubusername/netflix-frontend:latest

    - name: Push frontend image
      run: |
        docker push yourdockerhubusername/netflix-frontend:latest
